/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutCreate_postRouteImport } from './routes/_layout/create_post'
import { Route as LayoutProfileIndexRouteImport } from './routes/_layout/profile/index'
import { Route as LayoutProfileUserIdIndexRouteImport } from './routes/_layout/profile/$userId.index'
import { Route as LayoutProfileUserIdFollowingRouteImport } from './routes/_layout/profile/$userId.following'
import { Route as LayoutProfileUserIdFollowersRouteImport } from './routes/_layout/profile/$userId.followers'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreate_postRoute = LayoutCreate_postRouteImport.update({
  id: '/create_post',
  path: '/create_post',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileUserIdIndexRoute =
  LayoutProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProfileUserIdFollowingRoute =
  LayoutProfileUserIdFollowingRouteImport.update({
    id: '/profile/$userId/following',
    path: '/profile/$userId/following',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProfileUserIdFollowersRoute =
  LayoutProfileUserIdFollowersRouteImport.update({
    id: '/profile/$userId/followers',
    path: '/profile/$userId/followers',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/about': typeof AboutLazyRoute
  '/create_post': typeof LayoutCreate_postRoute
  '/search': typeof LayoutSearchRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/': typeof LayoutIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/profile/$userId/followers': typeof LayoutProfileUserIdFollowersRoute
  '/profile/$userId/following': typeof LayoutProfileUserIdFollowingRoute
  '/profile/$userId': typeof LayoutProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof AboutLazyRoute
  '/create_post': typeof LayoutCreate_postRoute
  '/search': typeof LayoutSearchRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/': typeof LayoutIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/profile/$userId/followers': typeof LayoutProfileUserIdFollowersRoute
  '/profile/$userId/following': typeof LayoutProfileUserIdFollowingRoute
  '/profile/$userId': typeof LayoutProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/about': typeof AboutLazyRoute
  '/_layout/create_post': typeof LayoutCreate_postRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/profile/$userId/followers': typeof LayoutProfileUserIdFollowersRoute
  '/_layout/profile/$userId/following': typeof LayoutProfileUserIdFollowingRoute
  '/_layout/profile/$userId/': typeof LayoutProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/about'
    | '/create_post'
    | '/search'
    | '/posts/$postId'
    | '/'
    | '/profile'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/create_post'
    | '/search'
    | '/posts/$postId'
    | '/'
    | '/profile'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/about'
    | '/_layout/create_post'
    | '/_layout/search'
    | '/posts/$postId'
    | '/_layout/'
    | '/_layout/profile/'
    | '/_layout/profile/$userId/followers'
    | '/_layout/profile/$userId/following'
    | '/_layout/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  AboutLazyRoute: typeof AboutLazyRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create_post': {
      id: '/_layout/create_post'
      path: '/create_post'
      fullPath: '/create_post'
      preLoaderRoute: typeof LayoutCreate_postRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$userId/': {
      id: '/_layout/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProfileUserIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$userId/following': {
      id: '/_layout/profile/$userId/following'
      path: '/profile/$userId/following'
      fullPath: '/profile/$userId/following'
      preLoaderRoute: typeof LayoutProfileUserIdFollowingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$userId/followers': {
      id: '/_layout/profile/$userId/followers'
      path: '/profile/$userId/followers'
      fullPath: '/profile/$userId/followers'
      preLoaderRoute: typeof LayoutProfileUserIdFollowersRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCreate_postRoute: typeof LayoutCreate_postRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutProfileUserIdFollowersRoute: typeof LayoutProfileUserIdFollowersRoute
  LayoutProfileUserIdFollowingRoute: typeof LayoutProfileUserIdFollowingRoute
  LayoutProfileUserIdIndexRoute: typeof LayoutProfileUserIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCreate_postRoute: LayoutCreate_postRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutProfileUserIdFollowersRoute: LayoutProfileUserIdFollowersRoute,
  LayoutProfileUserIdFollowingRoute: LayoutProfileUserIdFollowingRoute,
  LayoutProfileUserIdIndexRoute: LayoutProfileUserIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  AboutLazyRoute: AboutLazyRoute,
  PostsPostIdRoute: PostsPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
